# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f79ec7ae6528f9f923b1d4f327a0e1e71e18182597b919ff94dc61774bc97e8c440453673ede6b086c5200ed9f6d2e07d711b44af243c04fffceb05919b4968

test:
  secret_key_base: a35c9808eff6e7e7a15c23ff22c00812f562a60a052aa66c1dbca5a46634bee4c92d562c6e5640b8535958fe1680c8700b49abde87c56536e4579c06c6b40735

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
